[package]
name = "learning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aggregator"
path = "aggregator/src/lib.rs"
# to add more than one library, use workspaces 

[dependencies]
rand = "0.8.5"

